
event_data = [{
    "id": 1,
    "date": "2018-10-29",
    "city": "Chicago",
    "state": "Illinois",
    "venue": "Oodoo Arena",
    "attendance": 10577,
    "gate": 1398634
  }, {
    "id": 2,
    "date": "2018-08-31",
    "city": "Arlington",
    "state": "Virginia",
    "venue": "Jetpulse Arena",
    "attendance": 6326,
    "gate": 1548328
  }, {
    "id": 3,
    "date": "2019-03-29",
    "city": "Lansing",
    "state": "Michigan",
    "venue": "Plambee Arena",
    "attendance": 17075,
    "gate": 1127687
  }, {
    "id": 4,
    "date": "2019-06-26",
    "city": "Dallas",
    "state": "Texas",
    "venue": "Gabvine Arena",
    "attendance": 7145,
    "gate": 1797875
  }, {
    "id": 5,
    "date": "2018-10-08",
    "city": "Hagerstown",
    "state": "Maryland",
    "venue": "Jetwire Arena",
    "attendance": 18177,
    "gate": 1862218
  }, {
    "id": 6,
    "date": "2018-11-10",
    "city": "Alhambra",
    "state": "California",
    "venue": "Oloo Arena",
    "attendance": 18205,
    "gate": 400070
  }, {
    "id": 7,
    "date": "2018-11-04",
    "city": "Topeka",
    "state": "Kansas",
    "venue": "Gevee Arena",
    "attendance": 8562,
    "gate": 562307
  }, {
    "id": 8,
    "date": "2018-10-23",
    "city": "Silver Spring",
    "state": "Maryland",
    "venue": "Lajo Arena",
    "attendance": 9154,
    "gate": 1236040
  }, {
    "id": 9,
    "date": "2018-12-17",
    "city": "Hyattsville",
    "state": "Maryland",
    "venue": "Vimbo Arena",
    "attendance": 10290,
    "gate": 1272204
  }, {
    "id": 10,
    "date": "2019-05-14",
    "city": "Fort Myers",
    "state": "Florida",
    "venue": "Edgeblab Arena",
    "attendance": 16564,
    "gate": 685191
  }]

event_data.each do |event|
    Event.create(id: event[:id], date: event[:date], city: event[:city], state: event[:state], venue: event[:venue], attendance: event[:attendance], gate: event[:gate])
    # iterate over data and create a row with each dataset
end

competitor_data = [{
    "id": 1,
    "first_name": "Hazlett",
    "last_name": "Chatelain",
    "gender": "M",
    "weight_in_lbs": 185,
    "height_in_inches": 65,
    "reach_in_inches": 72,
    "age": 35,
    "wins": 16,
    "losses": 16
  }, {
    "id": 2,
    "first_name": "Aggie",
    "last_name": "Chaunce",
    "gender": "F",
    "weight_in_lbs": 125,
    "height_in_inches": 70,
    "reach_in_inches": 72,
    "age": 35,
    "wins": 9,
    "losses": 2
  }, {
    "id": 3,
    "first_name": "Mandel",
    "last_name": "Oblein",
    "gender": "M",
    "weight_in_lbs": 265,
    "height_in_inches": 73,
    "reach_in_inches": 73,
    "age": 36,
    "wins": 6,
    "losses": 18
  }, {
    "id": 4,
    "first_name": "Nik",
    "last_name": "Demsey",
    "gender": "M",
    "weight_in_lbs": 170,
    "height_in_inches": 74,
    "reach_in_inches": 68,
    "age": 38,
    "wins": 1,
    "losses": 4
  }, {
    "id": 5,
    "first_name": "Leonhard",
    "last_name": "De Nisco",
    "gender": "M",
    "weight_in_lbs": 155,
    "height_in_inches": 65,
    "reach_in_inches": 71,
    "age": 41,
    "wins": 14,
    "losses": 4
  }, {
    "id": 6,
    "first_name": "Verney",
    "last_name": "Rendbaek",
    "gender": "M",
    "weight_in_lbs": 185,
    "height_in_inches": 69,
    "reach_in_inches": 74,
    "age": 19,
    "wins": 29,
    "losses": 30
  }, {
    "id": 7,
    "first_name": "Taddeusz",
    "last_name": "Malicki",
    "gender": "M",
    "weight_in_lbs": 135,
    "height_in_inches": 66,
    "reach_in_inches": 64,
    "age": 39,
    "wins": 28,
    "losses": 11
  }, {
    "id": 8,
    "first_name": "Kayla",
    "last_name": "Bowbrick",
    "gender": "F",
    "weight_in_lbs": 125,
    "height_in_inches": 67,
    "reach_in_inches": 66,
    "age": 30,
    "wins": 5,
    "losses": 0
  }, {
    "id": 9,
    "first_name": "Zilvia",
    "last_name": "Espinosa",
    "gender": "F",
    "weight_in_lbs": 135,
    "height_in_inches": 69,
    "reach_in_inches": 69,
    "age": 39,
    "wins": 27,
    "losses": 20
  }, {
    "id": 10,
    "first_name": "Abel",
    "last_name": "Scogin",
    "gender": "M",
    "weight_in_lbs": 135,
    "height_in_inches": 69,
    "reach_in_inches": 68,
    "age": 34,
    "wins": 9,
    "losses": 15
  }, {
    "id": 11,
    "first_name": "Belvia",
    "last_name": "Mandre",
    "gender": "F",
    "weight_in_lbs": 145,
    "height_in_inches": 73,
    "reach_in_inches": 67,
    "age": 18,
    "wins": 14,
    "losses": 6
  }, {
    "id": 12,
    "first_name": "Saidee",
    "last_name": "Jeannard",
    "gender": "F",
    "weight_in_lbs": 205,
    "height_in_inches": 72,
    "reach_in_inches": 73,
    "age": 23,
    "wins": 2,
    "losses": 25
  }, {
    "id": 13,
    "first_name": "Elinore",
    "last_name": "Graalman",
    "gender": "F",
    "weight_in_lbs": 145,
    "height_in_inches": 67,
    "reach_in_inches": 68,
    "age": 38,
    "wins": 6,
    "losses": 22
  }, {
    "id": 14,
    "first_name": "Diann",
    "last_name": "Felmingham",
    "gender": "F",
    "weight_in_lbs": 125,
    "height_in_inches": 65,
    "reach_in_inches": 69,
    "age": 33,
    "wins": 6,
    "losses": 25
  }, {
    "id": 15,
    "first_name": "Carmen",
    "last_name": "Wannell",
    "gender": "F",
    "weight_in_lbs": 125,
    "height_in_inches": 64,
    "reach_in_inches": 69,
    "age": 38,
    "wins": 13,
    "losses": 20
  }, {
    "id": 16,
    "first_name": "Redford",
    "last_name": "Kingswood",
    "gender": "M",
    "weight_in_lbs": 170,
    "height_in_inches": 64,
    "reach_in_inches": 74,
    "age": 37,
    "wins": 9,
    "losses": 25
  }, {
    "id": 17,
    "first_name": "Wandie",
    "last_name": "Coyle",
    "gender": "F",
    "weight_in_lbs": 145,
    "height_in_inches": 68,
    "reach_in_inches": 64,
    "age": 20,
    "wins": 10,
    "losses": 23
  }, {
    "id": 18,
    "first_name": "Susi",
    "last_name": "Cribbins",
    "gender": "F",
    "weight_in_lbs": 145,
    "height_in_inches": 71,
    "reach_in_inches": 69,
    "age": 18,
    "wins": 21,
    "losses": 22
  }, {
    "id": 19,
    "first_name": "Almeda",
    "last_name": "Broxholme",
    "gender": "F",
    "weight_in_lbs": 185,
    "height_in_inches": 67,
    "reach_in_inches": 73,
    "age": 34,
    "wins": 23,
    "losses": 25
  }, {
    "id": 20,
    "first_name": "Ara",
    "last_name": "Huggon",
    "gender": "M",
    "weight_in_lbs": 205,
    "height_in_inches": 73,
    "reach_in_inches": 69,
    "age": 26,
    "wins": 14,
    "losses": 11
  }, {
    "id": 21,
    "first_name": "Margaretta",
    "last_name": "Scrymgeour",
    "gender": "F",
    "weight_in_lbs": 205,
    "height_in_inches": 67,
    "reach_in_inches": 72,
    "age": 42,
    "wins": 9,
    "losses": 27
  }, {
    "id": 22,
    "first_name": "Bary",
    "last_name": "Hinkens",
    "gender": "M",
    "weight_in_lbs": 265,
    "height_in_inches": 69,
    "reach_in_inches": 71,
    "age": 37,
    "wins": 16,
    "losses": 0
  }, {
    "id": 23,
    "first_name": "Gibb",
    "last_name": "Brydon",
    "gender": "M",
    "weight_in_lbs": 265,
    "height_in_inches": 74,
    "reach_in_inches": 69,
    "age": 34,
    "wins": 20,
    "losses": 25
  }, {
    "id": 24,
    "first_name": "Dillie",
    "last_name": "Danton",
    "gender": "M",
    "weight_in_lbs": 145,
    "height_in_inches": 72,
    "reach_in_inches": 68,
    "age": 41,
    "wins": 4,
    "losses": 28
  }, {
    "id": 25,
    "first_name": "Olva",
    "last_name": "Jedrzejczak",
    "gender": "F",
    "weight_in_lbs": 205,
    "height_in_inches": 67,
    "reach_in_inches": 68,
    "age": 41,
    "wins": 11,
    "losses": 9
  }, {
    "id": 26,
    "first_name": "Joye",
    "last_name": "Medhurst",
    "gender": "F",
    "weight_in_lbs": 155,
    "height_in_inches": 64,
    "reach_in_inches": 66,
    "age": 38,
    "wins": 28,
    "losses": 2
  }, {
    "id": 27,
    "first_name": "Benson",
    "last_name": "Bear",
    "gender": "M",
    "weight_in_lbs": 185,
    "height_in_inches": 74,
    "reach_in_inches": 74,
    "age": 18,
    "wins": 7,
    "losses": 0
  }, {
    "id": 28,
    "first_name": "Adey",
    "last_name": "O'Drought",
    "gender": "F",
    "weight_in_lbs": 170,
    "height_in_inches": 69,
    "reach_in_inches": 73,
    "age": 31,
    "wins": 0,
    "losses": 19
  }, {
    "id": 29,
    "first_name": "Dieter",
    "last_name": "Millington",
    "gender": "M",
    "weight_in_lbs": 185,
    "height_in_inches": 67,
    "reach_in_inches": 64,
    "age": 28,
    "wins": 12,
    "losses": 2
  }, {
    "id": 30,
    "first_name": "Gina",
    "last_name": "Simacek",
    "gender": "F",
    "weight_in_lbs": 155,
    "height_in_inches": 72,
    "reach_in_inches": 66,
    "age": 22,
    "wins": 17,
    "losses": 15
  }]

competitor_data.each do |competitor|
    Competitor.create(id: competitor[:id], first_name: competitor[:first_name], last_name: competitor[:last_name], gender: competitor[:gender], weight_in_lbs: competitor[:weight_in_lbs], height_in_inches: competitor[:height_in_inches], reach_in_inches: competitor[:reach_in_inches], age: competitor[:age], wins: competitor[:wins], losses: competitor[:losses])
    # iterate over data and create a row with each dataset
end



fight_data = [{
    "id": 1,
    "event_id": 3,
    "competitor_id": 19
  }, {
    "id": 2,
    "event_id": 6,
    "competitor_id": 20
  }, {
    "id": 3,
    "event_id": 6,
    "competitor_id": 28
  }, {
    "id": 4,
    "event_id": 10,
    "competitor_id": 18
  }, {
    "id": 5,
    "event_id": 1,
    "competitor_id": 1
  }, {
    "id": 6,
    "event_id": 8,
    "competitor_id": 21
  }, {
    "id": 7,
    "event_id": 10,
    "competitor_id": 18
  }, {
    "id": 8,
    "event_id": 6,
    "competitor_id": 13
  }, {
    "id": 9,
    "event_id": 8,
    "competitor_id": 25
  }, {
    "id": 10,
    "event_id": 6,
    "competitor_id": 5
  }, {
    "id": 11,
    "event_id": 6,
    "competitor_id": 16
  }, {
    "id": 12,
    "event_id": 7,
    "competitor_id": 10
  }, {
    "id": 13,
    "event_id": 10,
    "competitor_id": 26
  }, {
    "id": 14,
    "event_id": 6,
    "competitor_id": 4
  }, {
    "id": 15,
    "event_id": 7,
    "competitor_id": 27
  }, {
    "id": 16,
    "event_id": 7,
    "competitor_id": 1
  }, {
    "id": 17,
    "event_id": 10,
    "competitor_id": 8
  }, {
    "id": 18,
    "event_id": 7,
    "competitor_id": 8
  }, {
    "id": 19,
    "event_id": 1,
    "competitor_id": 13
  }, {
    "id": 20,
    "event_id": 9,
    "competitor_id": 28
  }, {
    "id": 21,
    "event_id": 9,
    "competitor_id": 19
  }, {
    "id": 22,
    "event_id": 3,
    "competitor_id": 16
  }, {
    "id": 23,
    "event_id": 6,
    "competitor_id": 29
  }, {
    "id": 24,
    "event_id": 4,
    "competitor_id": 29
  }, {
    "id": 25,
    "event_id": 8,
    "competitor_id": 4
  }, {
    "id": 26,
    "event_id": 5,
    "competitor_id": 10
  }, {
    "id": 27,
    "event_id": 8,
    "competitor_id": 11
  }, {
    "id": 28,
    "event_id": 8,
    "competitor_id": 28
  }, {
    "id": 29,
    "event_id": 7,
    "competitor_id": 1
  }, {
    "id": 30,
    "event_id": 2,
    "competitor_id": 28
  }, {
    "id": 31,
    "event_id": 7,
    "competitor_id": 6
  }, {
    "id": 32,
    "event_id": 2,
    "competitor_id": 24
  }, {
    "id": 33,
    "event_id": 1,
    "competitor_id": 13
  }, {
    "id": 34,
    "event_id": 1,
    "competitor_id": 28
  }, {
    "id": 35,
    "event_id": 9,
    "competitor_id": 27
  }, {
    "id": 36,
    "event_id": 5,
    "competitor_id": 14
  }, {
    "id": 37,
    "event_id": 8,
    "competitor_id": 4
  }, {
    "id": 38,
    "event_id": 6,
    "competitor_id": 1
  }, {
    "id": 39,
    "event_id": 4,
    "competitor_id": 12
  }, {
    "id": 40,
    "event_id": 2,
    "competitor_id": 25
  }, {
    "id": 41,
    "event_id": 4,
    "competitor_id": 27
  }, {
    "id": 42,
    "event_id": 1,
    "competitor_id": 6
  }, {
    "id": 43,
    "event_id": 10,
    "competitor_id": 26
  }, {
    "id": 44,
    "event_id": 4,
    "competitor_id": 21
  }, {
    "id": 45,
    "event_id": 4,
    "competitor_id": 30
  }, {
    "id": 46,
    "event_id": 6,
    "competitor_id": 16
  }, {
    "id": 47,
    "event_id": 4,
    "competitor_id": 20
  }, {
    "id": 48,
    "event_id": 1,
    "competitor_id": 29
  }, {
    "id": 49,
    "event_id": 2,
    "competitor_id": 12
  }, {
    "id": 50,
    "event_id": 9,
    "competitor_id": 5
  }, {
    "id": 51,
    "event_id": 5,
    "competitor_id": 7
  }, {
    "id": 52,
    "event_id": 3,
    "competitor_id": 17
  }, {
    "id": 53,
    "event_id": 5,
    "competitor_id": 6
  }, {
    "id": 54,
    "event_id": 4,
    "competitor_id": 3
  }, {
    "id": 55,
    "event_id": 3,
    "competitor_id": 7
  }, {
    "id": 56,
    "event_id": 10,
    "competitor_id": 7
  }, {
    "id": 57,
    "event_id": 9,
    "competitor_id": 28
  }, {
    "id": 58,
    "event_id": 7,
    "competitor_id": 27
  }, {
    "id": 59,
    "event_id": 8,
    "competitor_id": 22
  }, {
    "id": 60,
    "event_id": 8,
    "competitor_id": 11
  }, {
    "id": 61,
    "event_id": 6,
    "competitor_id": 30
  }, {
    "id": 62,
    "event_id": 9,
    "competitor_id": 5
  }, {
    "id": 63,
    "event_id": 4,
    "competitor_id": 2
  }, {
    "id": 64,
    "event_id": 6,
    "competitor_id": 20
  }, {
    "id": 65,
    "event_id": 8,
    "competitor_id": 22
  }, {
    "id": 66,
    "event_id": 8,
    "competitor_id": 19
  }, {
    "id": 67,
    "event_id": 4,
    "competitor_id": 26
  }, {
    "id": 68,
    "event_id": 9,
    "competitor_id": 30
  }, {
    "id": 69,
    "event_id": 10,
    "competitor_id": 6
  }, {
    "id": 70,
    "event_id": 9,
    "competitor_id": 10
  }, {
    "id": 71,
    "event_id": 1,
    "competitor_id": 17
  }, {
    "id": 72,
    "event_id": 9,
    "competitor_id": 19
  }, {
    "id": 73,
    "event_id": 4,
    "competitor_id": 28
  }, {
    "id": 74,
    "event_id": 7,
    "competitor_id": 10
  }, {
    "id": 75,
    "event_id": 10,
    "competitor_id": 6
  }, {
    "id": 76,
    "event_id": 8,
    "competitor_id": 6
  }, {
    "id": 77,
    "event_id": 9,
    "competitor_id": 21
  }, {
    "id": 78,
    "event_id": 1,
    "competitor_id": 29
  }, {
    "id": 79,
    "event_id": 5,
    "competitor_id": 12
  }, {
    "id": 80,
    "event_id": 2,
    "competitor_id": 5
  }, {
    "id": 81,
    "event_id": 6,
    "competitor_id": 17
  }, {
    "id": 82,
    "event_id": 10,
    "competitor_id": 6
  }, {
    "id": 83,
    "event_id": 6,
    "competitor_id": 27
  }, {
    "id": 84,
    "event_id": 5,
    "competitor_id": 15
  }, {
    "id": 85,
    "event_id": 2,
    "competitor_id": 10
  }, {
    "id": 86,
    "event_id": 7,
    "competitor_id": 29
  }, {
    "id": 87,
    "event_id": 2,
    "competitor_id": 27
  }, {
    "id": 88,
    "event_id": 4,
    "competitor_id": 6
  }, {
    "id": 89,
    "event_id": 4,
    "competitor_id": 29
  }, {
    "id": 90,
    "event_id": 6,
    "competitor_id": 28
  }, {
    "id": 91,
    "event_id": 1,
    "competitor_id": 10
  }, {
    "id": 92,
    "event_id": 10,
    "competitor_id": 3
  }, {
    "id": 93,
    "event_id": 3,
    "competitor_id": 29
  }, {
    "id": 94,
    "event_id": 2,
    "competitor_id": 9
  }, {
    "id": 95,
    "event_id": 2,
    "competitor_id": 22
  }, {
    "id": 96,
    "event_id": 6,
    "competitor_id": 15
  }, {
    "id": 97,
    "event_id": 3,
    "competitor_id": 18
  }, {
    "id": 98,
    "event_id": 1,
    "competitor_id": 21
  }, {
    "id": 99,
    "event_id": 3,
    "competitor_id": 15
  }, {
    "id": 100,
    "event_id": 2,
    "competitor_id": 2
  }]
fight_data.each do |fight|
    Fight.create(id: fight[:id], event_id: fight[:event_id], competitor_id: fight[:competitor_id])
end

